import Head from "next/head";
import { Register } from "../../src/Containers/Register";

export const SignUp = () => {
  return (
    <>
      <Head>
        <title>Registrar-se</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Register />
    </>
  );
};

export default SignUp;
