import Head from "next/head";
import { Dashboards } from "../../src/Containers/Dashboards";

export const Home = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboards />
    </>
  );
};

export default Home;
