import moment from "moment";
import Head from "next/head";
import { parseCookies } from "nookies";
import { useContext, useEffect, useState } from "react";
import { Box } from "../../src/components/Box";
import { Card } from "../../src/components/Card";
import { AreaChartGraph } from "../../src/components/Charts/Line";
import { Filter } from "../../src/components/Filter";
import { NavBar } from "../../src/components/Navbar";
import { AuthContext } from "../../src/context/AuthContext";
import { api } from "../../src/services/api";

interface FilterProps {
  date: string;
  total: number;
}

export const Home = () => {
  const [filter, setFilter] = useState("7");
  const [filterList, setFilterList] = useState<FilterProps[]>([]);

  const user = useContext(AuthContext);

  useEffect(() => {
    const fetchDate = async () => {
      const currentDate = moment().subtract(filter, "day").format("YYYY-MM-DD");
      try {
        const response = await api.get(
          `/user/api/users?endingDate=${currentDate}`
        );

        setFilterList(response.data);
      } catch (error) {
        console.log(error);
      }
    };
    fetchDate();
  }, [filter]);

  const handleChange = (event: string) => {
    return setFilter(event);
  };

  const total = filterList.reduce((accum, item) => accum + item.total, 0);

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        width="100%"
        position="absolute"
        background="var(--darkBlack)"
        padding="0 4rem 2rem 4rem"
      >
        <NavBar />
        <Box>
          <h1 style={{ color: "white" }}>{`${
            user && user.user?.gender === "Feminino"
              ? `Seja bem vinda, ${user.user?.name}`
              : `Seja bem vindo, ${user.user?.name}`
          }`}</h1>
        </Box>
        <Box>
          <Filter filter={filter} handleChange={handleChange} />
        </Box>

        <Box>
          <Card
            width="100%"
            height="500px"
            padding="1rem 1rem 0 1rem"
            title={`${total} Novos usuários`}
            description={
              filter === "7"
                ? "Na última semana"
                : filter === "15"
                ? "Nas últimas semanas"
                : filter === "30"
                ? "No último mês"
                : "Nos últimos meses"
            }
          >
            <AreaChartGraph data={filterList} />
          </Card>
        </Box>
      </Box>
      {/* <Dashboards /> */}
    </>
  );
};

export default Home;
